// Copyright 2026 the Runebender Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT

//! Bounded native workers for immutable compiled proofs.
//!
//! The application captures [`CompileProofInput`] while it owns the canonical
//! [`Project`](super::project::Project), then submits that owned value with an explicit document epoch.
//! This module never borrows application state or constructs a second project.
//! Its one worker compiles and renders only the immutable capture.
//!
//! A result always retains its submitted lineage.
//! The application/session adapter must compare that lineage with its current
//! epoch and revision before presenting a proof as current.
//! Queued jobs can be cancelled before work begins.
//! Running jobs cannot be cancelled because the font compiler is not
//! interruptible; cancellation then reports [`ProofJobCancelOutcome::TooLate`].

use std::collections::BTreeMap;
use std::panic::{AssertUnwindSafe, catch_unwind};
use std::sync::mpsc::{self, Receiver, SyncSender, TrySendError};
use std::sync::{Arc, Mutex};
use std::thread::JoinHandle;

use super::compiled_proof::{
    CompileProofInput, CompiledProof, CompiledProofRecipe, compile, prove,
};

/// Maximum accepted UTF-8 bytes in an opaque application document epoch.
pub const MAX_DOCUMENT_EPOCH_BYTES: usize = 256;
/// Maximum pending jobs accepted by one native worker queue.
pub const MAX_QUEUE_CAPACITY: usize = 16;
/// Maximum job handles and completed PNGs retained by one native worker queue.
pub const MAX_RETAINED_JOBS: usize = 32;

/// An opaque identifier for one retained proof job.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ProofJobHandle(u64);

impl ProofJobHandle {
    /// Return the monotonically increasing identifier for diagnostics.
    pub fn get(self) -> u64 {
        self.0
    }
}

/// The document lineage captured alongside a proof input.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProofJobLineage {
    /// The exact opaque application-owned document epoch.
    ///
    /// It is never parsed, hashed, truncated, or regenerated by this module.
    pub document_epoch: String,
    /// The canonical document revision captured into the proof input.
    pub document_revision: u64,
}

/// Owned immutable work for one compiled proof.
#[derive(Debug)]
pub struct ProofJobRequest {
    /// Application/document lineage captured with this input.
    pub lineage: ProofJobLineage,
    /// Canonical compiler input captured on the document-owning thread.
    pub input: CompileProofInput,
    /// Bounded shaping and rendering recipe.
    pub recipe: CompiledProofRecipe,
}

/// A job's current state, excluding retained image bytes.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProofJobStatus {
    /// The worker has not started this job.
    Queued,
    /// The worker is compiling or rendering this job.
    Running,
    /// The worker completed and retained an image.
    Completed,
    /// Compilation, shaping, outline extraction, or rendering failed.
    Failed,
    /// The job was cancelled while it was still queued.
    CancelledBeforeStart,
}

/// Why a request could not enter the bounded queue.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProofJobSubmitError {
    /// Queue capacity must be greater than zero.
    ZeroQueueCapacity,
    /// Retained-job capacity must be greater than zero.
    ZeroRetainedCapacity,
    /// Pending-work capacity exceeds [`MAX_QUEUE_CAPACITY`].
    QueueCapacityTooLarge {
        /// Submitted pending-work capacity.
        capacity: usize,
    },
    /// Retained-job capacity exceeds [`MAX_RETAINED_JOBS`].
    RetainedCapacityTooLarge {
        /// Submitted retained-job capacity.
        capacity: usize,
    },
    /// An application epoch must be nonempty and no longer than
    /// [`MAX_DOCUMENT_EPOCH_BYTES`] UTF-8 bytes.
    InvalidDocumentEpoch,
    /// The captured input revision differs from the supplied lineage.
    LineageRevisionMismatch {
        /// Revision carried by the immutable compiler input.
        input_revision: u64,
        /// Revision supplied by the application adapter.
        lineage_revision: u64,
    },
    /// The submitted recipe is invalid before worker work begins.
    InvalidRecipe(String),
    /// The bounded pending-work channel is full.
    QueueFull {
        /// Configured pending-work capacity.
        capacity: usize,
    },
    /// Retained handles, including completed PNGs, have reached their bound.
    RetainedJobsFull {
        /// Configured retained-job capacity.
        capacity: usize,
    },
    /// The queue has been shut down.
    Stopped,
}

/// The result of a cancellation request.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProofJobCancelOutcome {
    /// The queued job will never begin compiler work.
    CancelledBeforeStart,
    /// The job is already running, completed, or failed.
    ///
    /// The compiler cannot safely be interrupted, so its result remains
    /// associated with the original lineage.
    TooLate,
    /// The handle is not retained by this queue.
    UnknownHandle,
}

/// A terminal job outcome returned by [`ProofJobQueue::poll_completions`].
#[derive(Clone, Debug)]
pub enum ProofJobOutcome {
    /// A completed immutable proof and its bounded PNG image.
    Completed(Arc<CompiledProof>),
    /// A worker failure with no compiled snapshot or image.
    Failed(String),
    /// Cancellation prevented the worker from starting the job.
    CancelledBeforeStart,
}

/// A newly observed terminal result, retaining its original lineage.
#[derive(Clone, Debug)]
pub struct ProofJobCompletion {
    /// Handle assigned at submission.
    pub handle: ProofJobHandle,
    /// Original epoch/revision lineage; never rewritten when it completes late.
    pub lineage: ProofJobLineage,
    /// Terminal result and, for success, image bytes.
    pub outcome: ProofJobOutcome,
}

/// One coherent observation of a retained job, without consuming its completion.
#[derive(Clone, Debug)]
pub struct ProofJobInspection {
    /// Original submitted lineage.
    pub lineage: ProofJobLineage,
    /// State observed under the same lock as the outcome.
    pub status: ProofJobStatus,
    /// Terminal outcome when available, sharing rather than copying image bytes.
    pub outcome: Option<ProofJobOutcome>,
}

enum JobPhase {
    Queued(Box<ProofJobRequest>),
    Running,
    Completed(Arc<CompiledProof>),
    Failed(String),
    CancelledBeforeStart,
}

impl JobPhase {
    fn status(&self) -> ProofJobStatus {
        match self {
            Self::Queued(_) => ProofJobStatus::Queued,
            Self::Running => ProofJobStatus::Running,
            Self::Completed(_) => ProofJobStatus::Completed,
            Self::Failed(_) => ProofJobStatus::Failed,
            Self::CancelledBeforeStart => ProofJobStatus::CancelledBeforeStart,
        }
    }

    fn completion(&self) -> Option<ProofJobOutcome> {
        match self {
            Self::Completed(proof) => Some(ProofJobOutcome::Completed(proof.clone())),
            Self::Failed(error) => Some(ProofJobOutcome::Failed(error.clone())),
            Self::CancelledBeforeStart => Some(ProofJobOutcome::CancelledBeforeStart),
            Self::Queued(_) | Self::Running => None,
        }
    }
}

struct JobRecord {
    lineage: ProofJobLineage,
    phase: JobPhase,
    reported: bool,
}

struct QueueState {
    accepting: bool,
    next_handle: u64,
    jobs: BTreeMap<ProofJobHandle, JobRecord>,
}

struct SharedQueue {
    state: Mutex<QueueState>,
}

type ProofExecutor = dyn Fn(ProofJobRequest) -> Result<CompiledProof, String> + Send + 'static;

/// One bounded native proof worker.
///
/// A queue starts exactly one worker thread and never creates a thread per
/// job.
/// Dropping or shutting down a queue closes submissions and cancels queued
/// work without joining a possibly compiling worker on the caller's thread.
/// The one in-flight compiler call finishes naturally and its worker exits.
pub struct ProofJobQueue {
    shared: Arc<SharedQueue>,
    sender: Option<SyncSender<ProofJobHandle>>,
    worker: Option<JoinHandle<()>>,
    queue_capacity: usize,
    retained_capacity: usize,
}

impl std::fmt::Debug for ProofJobQueue {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ProofJobQueue")
            .field("queue_capacity", &self.queue_capacity)
            .field("retained_capacity", &self.retained_capacity)
            .field(
                "worker_finished",
                &self.worker.as_ref().is_none_or(JoinHandle::is_finished),
            )
            .finish_non_exhaustive()
    }
}

impl ProofJobQueue {
    /// Start one worker with explicit bounded pending and retained capacities.
    pub fn new(
        queue_capacity: usize,
        retained_capacity: usize,
    ) -> Result<Self, ProofJobSubmitError> {
        Self::with_executor(queue_capacity, retained_capacity, |request| {
            let snapshot = compile(request.input)?;
            prove(&snapshot, request.recipe)
        })
    }

    fn with_executor(
        queue_capacity: usize,
        retained_capacity: usize,
        executor: impl Fn(ProofJobRequest) -> Result<CompiledProof, String> + Send + 'static,
    ) -> Result<Self, ProofJobSubmitError> {
        if queue_capacity == 0 {
            return Err(ProofJobSubmitError::ZeroQueueCapacity);
        }
        if queue_capacity > MAX_QUEUE_CAPACITY {
            return Err(ProofJobSubmitError::QueueCapacityTooLarge {
                capacity: queue_capacity,
            });
        }
        if retained_capacity == 0 {
            return Err(ProofJobSubmitError::ZeroRetainedCapacity);
        }
        if retained_capacity > MAX_RETAINED_JOBS {
            return Err(ProofJobSubmitError::RetainedCapacityTooLarge {
                capacity: retained_capacity,
            });
        }
        let shared = Arc::new(SharedQueue {
            state: Mutex::new(QueueState {
                accepting: true,
                next_handle: 1,
                jobs: BTreeMap::new(),
            }),
        });
        let (sender, receiver) = mpsc::sync_channel(queue_capacity);
        let worker_shared = shared.clone();
        let executor: Box<ProofExecutor> = Box::new(executor);
        let worker = std::thread::spawn(move || worker_loop(worker_shared, receiver, executor));
        Ok(Self {
            shared,
            sender: Some(sender),
            worker: Some(worker),
            queue_capacity,
            retained_capacity,
        })
    }

    /// Submit owned immutable proof work without blocking on the worker.
    ///
    /// Call [`Self::discard`] after a terminal result is no longer needed to
    /// release its retained handle and image capacity.
    pub fn submit(&self, request: ProofJobRequest) -> Result<ProofJobHandle, ProofJobSubmitError> {
        if request.lineage.document_epoch.is_empty()
            || request.lineage.document_epoch.len() > MAX_DOCUMENT_EPOCH_BYTES
        {
            return Err(ProofJobSubmitError::InvalidDocumentEpoch);
        }
        if request.lineage.document_revision != request.input.document_revision() {
            return Err(ProofJobSubmitError::LineageRevisionMismatch {
                input_revision: request.input.document_revision(),
                lineage_revision: request.lineage.document_revision,
            });
        }
        request
            .recipe
            .validate()
            .map_err(ProofJobSubmitError::InvalidRecipe)?;

        let handle = {
            let mut state = self
                .shared
                .state
                .lock()
                .unwrap_or_else(|error| error.into_inner());
            if !state.accepting || self.sender.is_none() {
                return Err(ProofJobSubmitError::Stopped);
            }
            if state.jobs.len() >= self.retained_capacity {
                return Err(ProofJobSubmitError::RetainedJobsFull {
                    capacity: self.retained_capacity,
                });
            }
            let handle = ProofJobHandle(state.next_handle);
            state.next_handle = state
                .next_handle
                .checked_add(1)
                .expect("proof job handle overflow");
            state.jobs.insert(
                handle,
                JobRecord {
                    lineage: request.lineage.clone(),
                    phase: JobPhase::Queued(Box::new(request)),
                    reported: false,
                },
            );
            handle
        };

        let sender = self
            .sender
            .as_ref()
            .expect("checked while holding queue state");
        match sender.try_send(handle) {
            Ok(()) => Ok(handle),
            Err(TrySendError::Full(_)) => {
                self.remove_unstarted(handle);
                Err(ProofJobSubmitError::QueueFull {
                    capacity: self.queue_capacity,
                })
            }
            Err(TrySendError::Disconnected(_)) => {
                self.remove_unstarted(handle);
                Err(ProofJobSubmitError::Stopped)
            }
        }
    }

    /// Return the current typed status for a retained handle.
    pub fn status(&self, handle: ProofJobHandle) -> Option<ProofJobStatus> {
        self.shared
            .state
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .jobs
            .get(&handle)
            .map(|record| record.phase.status())
    }

    /// Inspect one job atomically without consuming another session's completion.
    ///
    /// Repeated calls retain the same terminal result until [`Self::discard`].
    pub fn inspect(&self, handle: ProofJobHandle) -> Option<ProofJobInspection> {
        self.shared
            .state
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .jobs
            .get(&handle)
            .map(|record| ProofJobInspection {
                lineage: record.lineage.clone(),
                status: record.phase.status(),
                outcome: record.phase.completion(),
            })
    }

    /// Cancel only queued work.
    ///
    /// A running font compiler cannot be interrupted safely, so a caller gets
    /// [`ProofJobCancelOutcome::TooLate`] and must reject a late result by its
    /// own epoch/revision policy if it is no longer current.
    pub fn cancel(&self, handle: ProofJobHandle) -> ProofJobCancelOutcome {
        let mut state = self
            .shared
            .state
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        let Some(record) = state.jobs.get_mut(&handle) else {
            return ProofJobCancelOutcome::UnknownHandle;
        };
        if matches!(record.phase, JobPhase::Queued(_)) {
            record.phase = JobPhase::CancelledBeforeStart;
            return ProofJobCancelOutcome::CancelledBeforeStart;
        }
        ProofJobCancelOutcome::TooLate
    }

    /// Return each terminal completion once, without discarding retained bytes.
    ///
    /// Polling again omits already reported handles.
    /// Use [`Self::discard`] after the application has consumed the outcome.
    pub fn poll_completions(&self) -> Vec<ProofJobCompletion> {
        let mut state = self
            .shared
            .state
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        state
            .jobs
            .iter_mut()
            .filter_map(|(handle, record)| {
                if record.reported {
                    return None;
                }
                let outcome = record.phase.completion()?;
                record.reported = true;
                Some(ProofJobCompletion {
                    handle: *handle,
                    lineage: record.lineage.clone(),
                    outcome,
                })
            })
            .collect()
    }

    /// Drop one retained terminal outcome and, for a completed job, its image.
    ///
    /// Returns false for unknown, queued, or running handles.
    pub fn discard(&self, handle: ProofJobHandle) -> bool {
        let mut state = self
            .shared
            .state
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        if state
            .jobs
            .get(&handle)
            .is_some_and(|record| record.phase.completion().is_some())
        {
            state.jobs.remove(&handle);
            true
        } else {
            false
        }
    }

    /// Stop accepting work and cancel queued jobs without waiting for a compiler call.
    ///
    /// Returns true only when the worker had already finished and was joined
    /// immediately.
    pub fn shutdown(mut self) -> bool {
        self.stop();
        self.join_finished_worker()
    }

    fn remove_unstarted(&self, handle: ProofJobHandle) {
        let mut state = self
            .shared
            .state
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        if state
            .jobs
            .get(&handle)
            .is_some_and(|record| matches!(record.phase, JobPhase::Queued(_)))
        {
            state.jobs.remove(&handle);
        }
    }

    fn stop(&mut self) {
        {
            let mut state = self
                .shared
                .state
                .lock()
                .unwrap_or_else(|error| error.into_inner());
            state.accepting = false;
            for record in state.jobs.values_mut() {
                if matches!(record.phase, JobPhase::Queued(_)) {
                    record.phase = JobPhase::CancelledBeforeStart;
                }
            }
        }
        // A worker that already received an item observes the cancelled state above.
        self.sender.take();
    }

    fn join_finished_worker(&mut self) -> bool {
        let Some(worker) = self.worker.take() else {
            return true;
        };
        if worker.is_finished() {
            let _ = worker.join();
            true
        } else {
            // Detaching here keeps a UI shutdown independent of an uninterruptible compiler.
            drop(worker);
            false
        }
    }
}

impl Drop for ProofJobQueue {
    fn drop(&mut self) {
        self.stop();
        let _ = self.join_finished_worker();
    }
}

fn worker_loop(
    shared: Arc<SharedQueue>,
    receiver: Receiver<ProofJobHandle>,
    executor: Box<ProofExecutor>,
) {
    while let Ok(handle) = receiver.recv() {
        let request = {
            let mut state = shared
                .state
                .lock()
                .unwrap_or_else(|error| error.into_inner());
            if !state.accepting {
                if let Some(record) = state.jobs.get_mut(&handle)
                    && matches!(record.phase, JobPhase::Queued(_))
                {
                    record.phase = JobPhase::CancelledBeforeStart;
                }
                continue;
            }
            let Some(record) = state.jobs.get_mut(&handle) else {
                continue;
            };
            match std::mem::replace(&mut record.phase, JobPhase::Running) {
                JobPhase::Queued(request) => *request,
                phase => {
                    record.phase = phase;
                    continue;
                }
            }
        };
        let result = catch_unwind(AssertUnwindSafe(|| executor(request)))
            .map_err(|_| {
                "proof worker stopped unexpectedly; no proof image was produced".to_string()
            })
            .and_then(|result| result);
        let mut state = shared
            .state
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        if let Some(record) = state.jobs.get_mut(&handle) {
            record.phase = match result {
                Ok(proof) => JobPhase::Completed(Arc::new(proof)),
                Err(error) => JobPhase::Failed(error),
            };
        }
    }
}

#[cfg(test)]
mod tests {
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::mpsc;
    use std::time::{Duration, Instant};

    use super::*;
    use crate::document::project::{Project, SourceInput};

    fn input() -> CompileProofInput {
        let project = Project::from_source(SourceInput::from_font(
            norad::Font::new(),
            "Test.ufo".into(),
        ));
        super::super::compiled_proof::capture(&project).expect("empty canonical input captures")
    }

    fn request(epoch: u64) -> ProofJobRequest {
        let input = input();
        ProofJobRequest {
            lineage: ProofJobLineage {
                document_epoch: format!("epoch-{epoch}"),
                document_revision: input.document_revision(),
            },
            input,
            recipe: CompiledProofRecipe {
                text: "A".into(),
                normalized_location: Vec::new(),
                right_to_left: false,
                features: Vec::new(),
                script: None,
                language: None,
            },
        }
    }

    fn proof(request: &ProofJobRequest) -> CompiledProof {
        CompiledProof {
            font_sha256: "sha256:test".into(),
            document_revision: request.input.document_revision(),
            compiler: request.input.compiler().clone(),
            canonical_input_sha256: request.input.canonical_input_sha256().into(),
            recipe: request.recipe.clone(),
            glyphs: Vec::new(),
            png: b"\x89PNG\r\n\x1a\n".to_vec(),
        }
    }

    fn poll_until(queue: &ProofJobQueue) -> ProofJobCompletion {
        let deadline = Instant::now() + Duration::from_secs(30);
        loop {
            if let Some(completion) = queue.poll_completions().into_iter().next() {
                return completion;
            }
            assert!(
                Instant::now() < deadline,
                "proof worker did not complete within 30 seconds"
            );
            std::thread::sleep(Duration::from_millis(5));
        }
    }

    #[test]
    fn inspection_does_not_consume_completions_and_is_coherent() {
        let queue = ProofJobQueue::with_executor(2, 3, |request| Ok(proof(&request))).unwrap();
        let first = queue.submit(request(1)).unwrap();
        let second = queue.submit(request(2)).unwrap();
        let deadline = Instant::now() + Duration::from_secs(5);
        for handle in [first, second] {
            loop {
                let view = queue.inspect(handle).unwrap();
                if view.status == ProofJobStatus::Completed {
                    assert!(matches!(view.outcome, Some(ProofJobOutcome::Completed(_))));
                    break;
                }
                assert!(view.outcome.is_none());
                assert!(Instant::now() < deadline);
                std::thread::yield_now();
            }
        }
        assert_eq!(
            queue.inspect(first).unwrap().lineage.document_epoch,
            "epoch-1"
        );
        assert_eq!(queue.poll_completions().len(), 2);
        assert!(queue.poll_completions().is_empty());
        assert!(queue.inspect(first).unwrap().outcome.is_some());
        assert!(queue.discard(first));
        assert!(queue.inspect(first).is_none());
        assert!(queue.inspect(second).is_some());
    }

    #[test]
    fn late_completion_retains_its_original_epoch_and_revision() {
        let (started_sender, started_receiver) = mpsc::channel();
        let (release_sender, release_receiver) = mpsc::channel();
        let queue = ProofJobQueue::with_executor(1, 2, move |request| {
            started_sender.send(()).unwrap();
            release_receiver.recv().unwrap();
            Ok(proof(&request))
        })
        .unwrap();
        let submitted = request(41);
        let lineage = submitted.lineage.clone();
        let handle = queue.submit(submitted).unwrap();
        started_receiver
            .recv_timeout(Duration::from_secs(1))
            .unwrap();
        assert_eq!(queue.status(handle), Some(ProofJobStatus::Running));
        release_sender.send(()).unwrap();
        let completion = poll_until(&queue);
        assert_eq!(completion.handle, handle);
        assert_eq!(completion.lineage, lineage);
        match completion.outcome {
            ProofJobOutcome::Completed(proof) => {
                assert_eq!(proof.document_revision, lineage.document_revision);
            }
            other => panic!("expected completed proof, got {other:?}"),
        }
    }

    #[test]
    fn failure_is_terminal_without_an_image() {
        let queue =
            ProofJobQueue::with_executor(1, 1, |_| Err("compiler fixture failed".into())).unwrap();
        let handle = queue.submit(request(1)).unwrap();
        let completion = poll_until(&queue);
        assert_eq!(completion.handle, handle);
        assert!(
            matches!(completion.outcome, ProofJobOutcome::Failed(ref error) if error == "compiler fixture failed")
        );
        assert_eq!(queue.status(handle), Some(ProofJobStatus::Failed));
        assert!(queue.discard(handle));
    }

    #[test]
    fn invalid_epochs_and_unbounded_capacities_are_rejected() {
        assert!(matches!(
            ProofJobQueue::new(MAX_QUEUE_CAPACITY + 1, 1),
            Err(ProofJobSubmitError::QueueCapacityTooLarge { capacity })
                if capacity == MAX_QUEUE_CAPACITY + 1
        ));
        assert!(matches!(
            ProofJobQueue::new(1, MAX_RETAINED_JOBS + 1),
            Err(ProofJobSubmitError::RetainedCapacityTooLarge { capacity })
                if capacity == MAX_RETAINED_JOBS + 1
        ));

        let queue = ProofJobQueue::new(1, 1).unwrap();
        let mut empty = request(1);
        empty.lineage.document_epoch.clear();
        assert_eq!(
            queue.submit(empty),
            Err(ProofJobSubmitError::InvalidDocumentEpoch)
        );
        let mut too_long = request(1);
        too_long.lineage.document_epoch = "x".repeat(MAX_DOCUMENT_EPOCH_BYTES + 1);
        assert_eq!(
            queue.submit(too_long),
            Err(ProofJobSubmitError::InvalidDocumentEpoch)
        );
    }

    #[test]
    fn panicking_executor_becomes_a_retained_failure() {
        let queue = ProofJobQueue::with_executor(1, 1, |_| -> Result<CompiledProof, String> {
            panic!("controlled proof worker panic");
        })
        .unwrap();
        let handle = queue.submit(request(1)).unwrap();
        let completion = poll_until(&queue);
        assert_eq!(completion.handle, handle);
        assert!(matches!(completion.outcome, ProofJobOutcome::Failed(_)));
        assert_eq!(queue.status(handle), Some(ProofJobStatus::Failed));
    }

    #[test]
    fn queue_and_retention_bounds_reject_new_work() {
        let (started_sender, started_receiver) = mpsc::channel();
        let (release_sender, release_receiver) = mpsc::channel();
        let queue = ProofJobQueue::with_executor(1, 2, move |request| {
            started_sender.send(()).unwrap();
            release_receiver.recv().unwrap();
            Ok(proof(&request))
        })
        .unwrap();
        let first = queue.submit(request(1)).unwrap();
        started_receiver
            .recv_timeout(Duration::from_secs(1))
            .unwrap();
        let second = queue.submit(request(1)).unwrap();
        assert_eq!(
            queue.submit(request(1)),
            Err(ProofJobSubmitError::RetainedJobsFull { capacity: 2 })
        );
        assert_eq!(
            queue.cancel(second),
            ProofJobCancelOutcome::CancelledBeforeStart
        );
        assert!(matches!(
            poll_until(&queue).outcome,
            ProofJobOutcome::CancelledBeforeStart
        ));
        release_sender.send(()).unwrap();
        let completion = poll_until(&queue);
        assert_eq!(completion.handle, first);
        assert!(queue.discard(first));
        assert!(queue.discard(second));

        let (hold_sender, hold_receiver) = mpsc::channel();
        let queue = ProofJobQueue::with_executor(1, 3, move |request| {
            hold_receiver.recv().unwrap();
            Ok(proof(&request))
        })
        .unwrap();
        let first = queue.submit(request(2)).unwrap();
        while queue.status(first) != Some(ProofJobStatus::Running) {
            std::thread::yield_now();
        }
        let _second = queue.submit(request(2)).unwrap();
        assert_eq!(
            queue.submit(request(2)),
            Err(ProofJobSubmitError::QueueFull { capacity: 1 })
        );
        hold_sender.send(()).unwrap();
    }

    #[test]
    fn cancellation_only_prevents_queued_work() {
        let (started_sender, started_receiver) = mpsc::channel();
        let (release_sender, release_receiver) = mpsc::channel();
        let calls = Arc::new(AtomicUsize::new(0));
        let executor_calls = calls.clone();
        let queue = ProofJobQueue::with_executor(1, 2, move |request| {
            executor_calls.fetch_add(1, Ordering::Relaxed);
            started_sender.send(()).unwrap();
            release_receiver.recv().unwrap();
            Ok(proof(&request))
        })
        .unwrap();
        let running = queue.submit(request(1)).unwrap();
        started_receiver
            .recv_timeout(Duration::from_secs(1))
            .unwrap();
        let queued = queue.submit(request(1)).unwrap();
        assert_eq!(
            queue.cancel(queued),
            ProofJobCancelOutcome::CancelledBeforeStart
        );
        assert_eq!(queue.cancel(running), ProofJobCancelOutcome::TooLate);
        let cancelled = poll_until(&queue);
        assert!(matches!(
            cancelled.outcome,
            ProofJobOutcome::CancelledBeforeStart
        ));
        release_sender.send(()).unwrap();
        let completed = poll_until(&queue);
        assert!(matches!(completed.outcome, ProofJobOutcome::Completed(_)));
        assert_eq!(calls.load(Ordering::Relaxed), 1);
    }

    #[test]
    fn worker_compiles_and_renders_an_immutable_real_proof() {
        let project = Project::load(&crate::testing::fonts::designspace()).unwrap();
        let input = super::super::compiled_proof::capture(&project).unwrap();
        let queue = ProofJobQueue::new(1, 1).unwrap();
        let handle = queue
            .submit(ProofJobRequest {
                lineage: ProofJobLineage {
                    document_epoch: "live-epoch-9".into(),
                    document_revision: input.document_revision(),
                },
                input,
                recipe: CompiledProofRecipe {
                    text: "AVATAR".into(),
                    normalized_location: vec![-1.0],
                    right_to_left: false,
                    features: Vec::new(),
                    script: Some("latn".into()),
                    language: None,
                },
            })
            .unwrap();
        let completion = poll_until(&queue);
        assert_eq!(completion.handle, handle);
        match completion.outcome {
            ProofJobOutcome::Completed(proof) => {
                assert!(proof.png.starts_with(b"\x89PNG\r\n\x1a\n"));
                assert!(!proof.glyphs.is_empty());
                assert_eq!(
                    proof.document_revision,
                    completion.lineage.document_revision
                );
            }
            other => panic!("expected compiled proof, got {other:?}"),
        }
    }
}
